#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BambuShootProject.Droid.Resource", IsApplication=true)]

namespace BambuShootProject.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BambuCrossSection = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BambuShootIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int database = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Image1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Image2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int LOGO_BambuShoot = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int test1 = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000f
			public const int BambuShootLogo = 2131165199;
			
			// aapt resource value: 0x7f070008
			public const int Instructions = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int LinearLayout1 = 2131165193;
			
			// aapt resource value: 0x7f070000
			public const int LinearLayoutinputcalibration1 = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int addImageBtn = 2131165196;
			
			// aapt resource value: 0x7f070013
			public const int databasebtn = 2131165203;
			
			// aapt resource value: 0x7f07000e
			public const int editText_Imagetitle = 2131165198;
			
			// aapt resource value: 0x7f070004
			public const int editText_Nameofspecies = 2131165188;
			
			// aapt resource value: 0x7f07000d
			public const int editText_Username = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int editText_dateofharvest = 2131165189;
			
			// aapt resource value: 0x7f070003
			public const int editText_location = 2131165187;
			
			// aapt resource value: 0x7f07000b
			public const int imageView1 = 2131165195;
			
			// aapt resource value: 0x7f070010
			public const int instructionsbtn = 2131165200;
			
			// aapt resource value: 0x7f07000a
			public const int linearLayout2 = 2131165194;
			
			// aapt resource value: 0x7f070001
			public const int linearLayoutinputcalibration2 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int loadedimageview = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int loadimageBtn = 2131165190;
			
			// aapt resource value: 0x7f070012
			public const int mydatareportlibrarybtn = 2131165202;
			
			// aapt resource value: 0x7f070011
			public const int processnewimagebtn = 2131165201;
			
			// aapt resource value: 0x7f070007
			public const int testingdata = 2131165191;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int InputCalibration = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Instruction_Dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int LoadImage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050005
			public const int date_harvest = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int date_harvest_placeholder = 2131034122;
			
			// aapt resource value: 0x7f050002
			public const int image_title = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int imagetitle_placeholder = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int location = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int location_placeholder = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int name_species = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int name_species_placeholder = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int username = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int username_placeholder = 2131034118;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
