#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BambuShootProject.Droid.Resource", IsApplication=true)]

namespace BambuShootProject.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ClassLibrary.Resource.String.ApplicationName = global::BambuShootProject.Droid.Resource.String.ApplicationName;
			global::ClassLibrary.Resource.String.Hello = global::BambuShootProject.Droid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int BambuCrossSection = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int BambuShootIcon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int database = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Image1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Image2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int LOGO_BambuShoot = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int test1 = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08001b
			public const int BWRadioBtn = 2131230747;
			
			// aapt resource value: 0x7f080027
			public const int BambuShootLogo = 2131230759;
			
			// aapt resource value: 0x7f080003
			public const int CreateBtn = 2131230723;
			
			// aapt resource value: 0x7f080028
			public const int CreateUserBtn = 2131230760;
			
			// aapt resource value: 0x7f080000
			public const int CreateUsertxt = 2131230720;
			
			// aapt resource value: 0x7f08001a
			public const int GSRadioBtn = 2131230746;
			
			// aapt resource value: 0x7f08001e
			public const int Instructions = 2131230750;
			
			// aapt resource value: 0x7f080004
			public const int LinearLayout1 = 2131230724;
			
			// aapt resource value: 0x7f080011
			public const int LinearLayoutinputcalibration1 = 2131230737;
			
			// aapt resource value: 0x7f080026
			public const int Noimageselected = 2131230758;
			
			// aapt resource value: 0x7f080002
			public const int PasswordEdt = 2131230722;
			
			// aapt resource value: 0x7f080007
			public const int SearchBtn = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int SearchEdttxt = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int SearchLinearLayout = 2131230725;
			
			// aapt resource value: 0x7f080001
			public const int UsernameEdt = 2131230721;
			
			// aapt resource value: 0x7f080020
			public const int addImageBtn = 2131230752;
			
			// aapt resource value: 0x7f080017
			public const int cropBtn = 2131230743;
			
			// aapt resource value: 0x7f08002c
			public const int databasebtn = 2131230764;
			
			// aapt resource value: 0x7f080025
			public const int datePicker1 = 2131230757;
			
			// aapt resource value: 0x7f08000f
			public const int dateofharvesttxtview = 2131230735;
			
			// aapt resource value: 0x7f080021
			public const int editText_Imagetitle = 2131230753;
			
			// aapt resource value: 0x7f080023
			public const int editText_Nameofspecies = 2131230755;
			
			// aapt resource value: 0x7f080022
			public const int editText_location = 2131230754;
			
			// aapt resource value: 0x7f08001c
			public const int editText_threshold = 2131230748;
			
			// aapt resource value: 0x7f080014
			public const int editedimageview = 2131230740;
			
			// aapt resource value: 0x7f080024
			public const int harvestdate = 2131230756;
			
			// aapt resource value: 0x7f080008
			public const int horizontalScrollView1 = 2131230728;
			
			// aapt resource value: 0x7f08001f
			public const int imageView1 = 2131230751;
			
			// aapt resource value: 0x7f08000c
			public const int imagetitletxtview = 2131230732;
			
			// aapt resource value: 0x7f080016
			public const int imagetransform = 2131230742;
			
			// aapt resource value: 0x7f080029
			public const int instructionsbtn = 2131230761;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayout2 = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int linearLayout3 = 2131230729;
			
			// aapt resource value: 0x7f080012
			public const int linearLayoutinputcalibration2 = 2131230738;
			
			// aapt resource value: 0x7f080010
			public const int listViewReports = 2131230736;
			
			// aapt resource value: 0x7f080013
			public const int loadedimageview = 2131230739;
			
			// aapt resource value: 0x7f08001d
			public const int loadimageBtn = 2131230749;
			
			// aapt resource value: 0x7f08000d
			public const int locationtxtview = 2131230733;
			
			// aapt resource value: 0x7f080032
			public const int menu_refresh = 2131230770;
			
			// aapt resource value: 0x7f08002b
			public const int mydatareportlibrarybtn = 2131230763;
			
			// aapt resource value: 0x7f08000e
			public const int nameofspeciestxtview = 2131230734;
			
			// aapt resource value: 0x7f08002a
			public const int processnewimagebtn = 2131230762;
			
			// aapt resource value: 0x7f080019
			public const int radioGroup1 = 2131230745;
			
			// aapt resource value: 0x7f080018
			public const int rotateBtn = 2131230744;
			
			// aapt resource value: 0x7f080015
			public const int scrollView1 = 2131230741;
			
			// aapt resource value: 0x7f080031
			public const int txtDateofHarvest = 2131230769;
			
			// aapt resource value: 0x7f08002e
			public const int txtImageTitle = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int txtLocation = 2131230767;
			
			// aapt resource value: 0x7f080030
			public const int txtNameofspecies = 2131230768;
			
			// aapt resource value: 0x7f08002d
			public const int txtUsername = 2131230765;
			
			// aapt resource value: 0x7f08000b
			public const int usernametxtview = 2131230731;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CreateUser = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DatabaseLibrary = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DataReportLibrary = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DataReportPage = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int InputCalibration = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Instruction_Dialog = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int LoadImage = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Row_list_Report_DB = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int activity_DB = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050007
			public const int date_harvest = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int date_harvest_placeholder = 2131034126;
			
			// aapt resource value: 0x7f050004
			public const int image_title = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int imagetitle_placeholder = 2131034123;
			
			// aapt resource value: 0x7f050005
			public const int location = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int location_placeholder = 2131034124;
			
			// aapt resource value: 0x7f050006
			public const int name_species = 2131034118;
			
			// aapt resource value: 0x7f05000d
			public const int name_species_placeholder = 2131034125;
			
			// aapt resource value: 0x7f050008
			public const int threshold = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int threshold_placeholder = 2131034121;
			
			// aapt resource value: 0x7f050003
			public const int username = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int username_placeholder = 2131034122;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
